version: '3.8'
services:
  redisgo:
    build: ./RedisGo
    ports:
      - "6379:6379"
    restart: unless-stopped

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - redisgo
    environment:
      - REDIS_HOST=redisgo
      - REDIS_PORT=6379
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - API_URL=http://backend:8000
    restart: unless-stopped
